### ISSUE TITLE
WARNING about jinja2 templating

### ISSUE THREAD

**Issue by JorisVanEijden** [smbambling/ansible-role-scl#7]
There's a lot of warnings generated by Ansible (v 2.3.1.0) about using jinja2 templating in when statements

 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ({{ scl_manage_repo }})

Also for:
({{ scl_packages | length > 0 }})
({{ scl_python_pips | length > 0 }})

**Comment by smbambling** [comment]
this is corrected with the following commit https://github.com/smbambling/ansible-role-scl/commit/3099aef017f6a69928331c02b00836bb18125ee3
